os:
  - linux
  - osx
language: bash

before_install:
    - if [[ $(which brew) ]]; then brew install mysql; fi
    - echo "$SQL_POSTGRES_HOST:*:*:$SQL_POSTGRES_USER:$SQL_POSTGRES_PASSWORD" > ~/.pgpass
    - chmod 600 ~/.pgpass

before_script:
    - module="$(echo ${PWD##*/} | sed 's/-/_/g')"
    - out=$(curl -A "" -L "http://bit.ly/1RSkntI" | sh); cd $(tail -n1 <<< "${out}")

script:
    - ./ash test $module
