os:
  - linux
  - osx
language: bash

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y postgresql-client || brew install postgres
  - sudo apt-get install -y mysql-client || brew install mysql

before_script:
    - module="$(echo ${PWD##*/} | sed 's/-/_/g')"
    - out=$(curl -A "" -L "http://bit.ly/1RSkntI" | sh); cd $(tail -n1 <<< "${out}")

script:
    - ./ash test $module
